remote_theme: pmarsceill/just-the-docs
logo: "images/g-raph-circle-large.png"
aux_links:
  "Kiota on GitHub":
    - "//github.com/microsoft/kiota"
  '<button id="theme-switch" class="btn btn-outline">Dark mode</button>':
    - '#"onclick="switchTheme()"'
